name: 🐛 Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for helping us squash this bug! 🐞

        We appreciate you taking the time to report this issue. To help us diagnose and fix it effectively, please provide as much detail as possible by answering the following questions.

        ---
  - type: input
    attributes:
      label: Version
      description: What version of the software/library are you experiencing this issue on? (e.g., `v2.5.1`, commit `a1b2c3d`)
    validations:
      required: true
  - type: input
    attributes:
      label: Operating System
      description: What operating system and version are you using? (e.g., `Windows 11`, `macOS Sonoma 14.5`, `Ubuntu 24.04`)
    validations:
      required: true
  - type: input
    attributes:
      label: Browser (if applicable)
      description: If the issue is browser-specific, please specify the browser name and version. (e.g., `Chrome 125.0.x`, `Firefox 126.0`, `Safari 17.x`)
  - type: dropdown
    attributes:
      label: Environment
      description: In which environment did you encounter this bug?
      multiple: true
      options:
        - Browser
        - Node.js (version: _____)
        - Desktop Application (platform: _____)
        - Mobile Application (iOS version: _____)
        - Mobile Application (Android version: _____)
        - Command Line Interface (CLI version: _____)
        - Other (please specify below)
    validations:
      required: true
  - type: input
    attributes:
      label: Other Environment (if selected above)
      description: Please specify the environment if 'Other' was selected.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Detailed Steps to Reproduce
      description: Provide a numbered list of precise steps that lead to the bug. The more detail, the better! Include any specific actions, inputs, or configurations.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Outcome
      description: Describe what you expected to happen after performing the steps above.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Outcome
      description: Describe what actually happened. Please include any error messages, unexpected behavior, or visual anomalies. If possible, provide textual output or attach relevant screenshots/screen recordings.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Severity
      description: How severe do you consider this bug to be?
      options:
        - Critical (renders the product unusable)
        - Major (significantly impacts functionality)
        - Minor (cosmetic issue or small inconvenience)
        - Trivial (very minor issue)
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Frequency
      description: How often does this bug occur?
      options:
        - Always (100% of the time)
        - Often (frequently, but not always)
        - Sometimes (intermittently)
        - Rarely (only occasionally)
        - Once (happened only a single time)
    validations:
      required: true
  - type: textarea
    attributes:
      label: Potential Cause (Optional)
      description: If you have any educated guesses or insights into the underlying cause of the bug, please share them here. This can be very helpful!
  - type: textarea
    attributes:
      label: Screenshots/Screen Recordings (Optional)
      description: If the bug is visual, please attach any relevant screenshots or screen recordings to help illustrate the issue.
  - type: textarea
    attributes:
      label: Additional Context or Workarounds (Optional)
      description: Include any other relevant information, such as temporary workarounds you've discovered, related issues you've seen, or specific configurations that might be relevant.