name: Test, Coverage, and Reporting

permissions:
  contents: write
  pull-requests: write
  checks: write
  statuses: write

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  run-tests:

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
      fail-fast: false

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Free up disk space on runner
        run: |
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/.ghcup

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache dependencies
        uses: actions/cache@v4.2.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-python-${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [ -f "./scripts/setup_cuda.sh" ]; then
            chmod +x ./scripts/setup_cuda.sh
            ./scripts/setup_cuda.sh
          fi
          pip install .[cuda,dev] --extra-index-url https://pypi.nvidia.com

      - name: Run tests and generate coverage report
        run: |
          pytest --cov=definers --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
